name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Run actionlint
        run: actionlint

  scan:
    uses: ./.github/workflows/scan.yml
    permissions:
      contents: read
      security-events: write

  codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      security-events: write
    with:
      languages: '["actions"]'
